## Array with 10 zeros

In [4]:
import numpy as np

zeros = np.zeros(10)
print("Zeros:\n", zeros, "\n")


Zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



## Array with fives only

In [5]:
fives = np.ones(10) * 5
print("Fives:\n", fives, "\n")

Fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 



## Array with digits from 10 to 50

In [6]:
tableTenToFifty = np.arange(10, 51, 1)
print("Ten to Fifty array:\n", tableTenToFifty, "\n")

Ten to Fifty array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] 



## 3x3 Array with digits from 0 to 8

In [7]:
matrix = np.arange(0, 9, 1).reshape((3, 3))
print("3x3 matrix 0 to 8:\n", matrix, "\n")

3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 



## 3x3 Array with zeros only

In [8]:
d3zerosMatrix = np.zeros((3, 3))
print("3x3 matrix zeros:\n", d3zerosMatrix, "\n")

3x3 matrix zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



## 3x3 Identity Array

In [17]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 5x5 Array gauss distributed values

In [9]:
gauss = np.random.normal(size=(5, 5))
print("Gaus:\n", gauss, "\n")

Gaus:
 [[-1.64541373 -0.71159836  1.43721832  1.72695958 -0.19093727]
 [-0.02218672 -1.48286709  1.53063345  0.36140211  0.15115885]
 [ 1.08846471  0.1907834   1.67834417  2.50660977  0.17166069]
 [ 0.56441761  0.64711995  2.2529269   0.69158345 -1.33127134]
 [ 0.63852894 -0.10946073  0.2206063   1.8070884   0.6170043 ]] 



## 10x10 Array digits from 0.01 to 1

In [10]:
tenXTenArray = np.arange(0.01, 1.01, 0.01).reshape((10, 10))
print("10x10 Array:\n", tenXTenArray, "\n")

10x10 Array:
 [[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]] 



### Array with digits from 0 to 1 included, linear distributed

In [11]:
linspaceValues = np.linspace(0, 1, 20)
print("Evenly spaced values:\n", linspaceValues, "\n")

Evenly spaced values:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ] 



### Array with random values from 1 to 25 (reshape(),sum(),mean(), std(), sum(axis))

In [12]:
randomNumbers1To25 = np.random.randint(1, 26, 25)
print("Random numbers from 1 to 25:\n", randomNumbers1To25, "\n")
randomNumbers1To25 = randomNumbers1To25.reshape((5, 5))
print("Reshaped random numbers:\n", randomNumbers1To25, "\n")
print("Sum of all values:\n", randomNumbers1To25.sum(), "\n")
print("Mean of all values:\n", randomNumbers1To25.mean(), "\n")
print("Deviation of all values:\n", randomNumbers1To25.std(), "\n")

sumOfColumns = randomNumbers1To25.sum(axis=0)
print("Sum of columns:\n", sumOfColumns, "\n")

Random numbers from 1 to 25:
 [13 21 11 18 17 15  7 12 25 14  1 23  9 12 12  9  2 22 16 19 10  9 20  8
  1] 

Reshaped random numbers:
 [[13 21 11 18 17]
 [15  7 12 25 14]
 [ 1 23  9 12 12]
 [ 9  2 22 16 19]
 [10  9 20  8  1]] 

Sum of all values:
 326 

Mean of all values:
 13.04 

Deviation of all values:
 6.52061346807185 

Sum of columns:
 [48 62 74 79 63] 



### Array with random values from 0 to 100 (median(), min(), max())

In [13]:
randomNumbers5x5 = np.random.randint(0, 101, (5, 5))
print("5 x 5 random numbers:\n", randomNumbers5x5, "\n")
print("Median of the random numbers:\n", np.median(randomNumbers5x5), "\n")
print("Min of the random numbers:\n", np.min(randomNumbers5x5), "\n")
print("Max of the random numbers:\n", np.max(randomNumbers5x5), "\n")

5 x 5 random numbers:
 [[47  4 68 23  1]
 [73 89 50 35 66]
 [61 79 69 38  9]
 [38 38 80 67 91]
 [45  1 26 52 54]] 

Median of the random numbers:
 50.0 

Min of the random numbers:
 1 

Max of the random numbers:
 91 



## Random numbers with random axis size (transposition)

In [14]:

def set_y():
    y_axis = np.random.randint(2, 11)
    if y_axis != x:
        return y_axis
    else:
        y_axis = set_y()
        return y_axis


x = np.random.randint(2, 11)
y = set_y()
randomNumbersRandomAxis = np.random.randint(0, 101, (x, y))
print("Random numbers with random axis size:\n", randomNumbersRandomAxis, "\n")
print("Transposition:\n", randomNumbersRandomAxis.transpose(), "\n")

Random numbers with random axis size:
 [[35  1 17 24]
 [91  8 90 90]
 [67 22 77 55]
 [50 77 36  7]
 [39 64 31 86]
 [40 58  9 28]] 

Transposition:
 [[35 91 67 50 39 40]
 [ 1  8 22 77 64 58]
 [17 90 77 36 31  9]
 [24 90 55  7 86 28]] 



## Matrix addition

In [15]:
matrixX = np.random.randint(2, 11)
matrixY = np.random.randint(2, 11)
matrixA = np.random.randint(0, 101, (matrixX, matrixY))
print("Matrix A + Matrix B:\n", matrixA, "\n")
matrixB = np.random.randint(0, 101, (matrixX, matrixY))
print("Matrix A + Matrix B:\n", matrixB, "\n")
print("Matrix A + Matrix B:\n", matrixA + matrixB, "\n")

Matrix A + Matrix B:
 [[43 91]
 [96 53]
 [11 69]] 

Matrix A + Matrix B:
 [[51 68]
 [ 2 60]
 [12 99]] 

Matrix A + Matrix B:
 [[ 94 159]
 [ 98 113]
 [ 23 168]] 



## Matrix multiplication

In [16]:
matrixXMultiply = np.random.randint(2, 11)
matrixYMultiply = np.random.randint(2, 11)
matrixAMultiply = np.random.randint(0, 101, (matrixXMultiply, matrixYMultiply))
print("Matrix A for multiplication:\n", matrixAMultiply, "\n")
matrixBMultiply = np.random.randint(0, 101, (matrixYMultiply, matrixXMultiply))
print("Matrix B for multiplication:\n", matrixBMultiply, "\n")
print("Matrix A * Matrix B with np.matmul():\n", np.matmul(matrixAMultiply, matrixBMultiply), "\n")
print("Matrix A * Matrix B with np.dot():\n", np.dot(matrixAMultiply, matrixBMultiply), "\n")


Matrix A for multiplication:
 [[72 98]
 [20 63]
 [46 51]
 [52 26]
 [14 39]
 [94 75]
 [93 72]
 [19 26]
 [38 89]] 

Matrix B for multiplication:
 [[63 57 90 14 71  9 66 13 51]
 [84 99 97 43 18  8 34 80 96]] 

Matrix A * Matrix B with np.matmul():
 [[12768 13806 15986  5222  6876  1432  8084  8776 13080]
 [ 6552  7377  7911  2989  2554   684  3462  5300  7068]
 [ 7182  7671  9087  2837  4184   822  4770  4678  7242]
 [ 5460  5538  7202  1846  4160   676  4316  2756  5148]
 [ 4158  4659  5043  1873  1696   438  2250  3302  4458]
 [12222 12783 15735  4541  8024  1446  8754  7222 11994]
 [11907 12429 15354  4398  7899  1413  8586  6969 11655]
 [ 3381  3657  4232  1384  1817   379  2138  2327  3465]
 [ 9870 10977 12053  4359  4300  1054  5534  7614 10482]] 

Matrix A * Matrix B with np.dot():
 [[12768 13806 15986  5222  6876  1432  8084  8776 13080]
 [ 6552  7377  7911  2989  2554   684  3462  5300  7068]
 [ 7182  7671  9087  2837  4184   822  4770  4678  7242]
 [ 5460  5538  7202  1846  4160